#!/usr/bin/env Rscript
# Build the FULL 1,522-sample rMATS atlas from raw per-run outputs.
#
# WHY THIS EXISTS. The aggregated `<ET>.MATS.JC.txt.csv.gz` files in the rMATS tree are cohort-subset
# (415 uuids): `02-3-rmats-event-filtering.Rmd` applies `keep_idx <- which(uuids %in% rna_to_use)`
# when it builds them, which was an OOM fix, not a scientific choice. The full-cohort files that do
# exist (`*.allsample.bak`, `all.SE`, `.SE`) are orphaned output of the pre-fix code and cannot be
# regenerated by the current pipeline. For a data release the full set has to be rebuilt from source.
#
# WHY IT IS A SEPARATE SCRIPT AND NOT A FLAG ON 02-3. Parameterising 02-3 would be the principled
# route -- it is the same transform, and this project's own precedent (the injection hook living
# inside 09s-ridge-screen.R rather than being re-implemented) argues against duplication. But 02-3 is
# a declared input of `rule rmats_event_filtering`, whose outputs feed `prepare_aggregation` and
# therefore everything; editing it invalidates the whole pipeline, and `--touch` is explicitly ruled
# out for a whole-pipeline cascade (revision/deferred-cosmetic-edits.md). Duplication is acceptable
# HERE and only here because (a) the output is a frozen one-time snapshot, so there is nothing for it
# to drift into, and (b) the duplication is TESTABLE -- see --verify below. If 02-3 ever re-runs for a
# substantive reason, fold the parameterisation in and retire this script.
#
# --verify IS THE GATE. Restricted to rna_to_use this must reproduce the live cohort-subset file. If
# it does not, the two implementations have diverged and the full output must not be trusted.
#
# MEMORY. The original OOM came from holding `n_events x n_samples_in_run` wide tables across 4-8
# concurrent forks (SE: ~150k events x 441 samples, killed at 48 GB). Here: serial over runs, and
# CHUNKED over samples within a run, so peak is n_events x SAMPLE_CHUNK x 3 measure vars. SE at
# chunk 100 is ~450 MB, against the 48 GB that died. Fork width is not the lever; chunk width is.
#
# WRITES NOWHERE THE PIPELINE READS. Output goes to processed_data/atlas/, never to the rMATS tree's
# `<ET>.MATS.JC.txt.csv.gz` cache. NB the reason is hygiene, not safety: 02-3 line ~578 re-filters
# that cache to rna_to_use immediately after reading it, with a comment saying the filter exists
# precisely to "cover a stale all-sample cache". So a full-cohort file there would NOT corrupt
# downstream results. It still does not belong in the input tree, and per-run outputs here are
# resumable, which the single cache file is not.
#
# NB `rna_to_use` is 441, not 415: it is the QC/metadata cohort (RNA-Seq assays of epirrs with >= 8
# files). The modelled 415 is the INTERSECTION of that with what rMATS actually quantified -- the 26
# AMED-CREST samples are absent from the rMATS runs entirely.

suppressPackageStartupMessages(library(data.table))
setDTthreads(as.integer(Sys.getenv("ATLAS_DT_THREADS", "4")))

args        <- commandArgs(trailingOnly = TRUE)
VERIFY      <- "--verify" %in% args
tf          <- Sys.getenv("TRANSCRIPT_FILTER", "biotype_filtered")
atlas_root  <- Sys.getenv("RMATS_ATLAS_ROOT", "/nfs/data/IHEC/RNAseq/rmats")
cmd_file    <- Sys.getenv("RMATS_COMMANDS", "data/rmats_split_post_commands.tsv")
out_root    <- Sys.getenv("ATLAS_FULL_OUT", file.path("processed_data", "atlas", tf))
SAMPLE_CHUNK <- as.integer(Sys.getenv("ATLAS_SAMPLE_CHUNK", "100"))
EVENT_TYPES <- strsplit(Sys.getenv("ATLAS_EVENT_TYPES", "SE,RI,A3SS,A5SS,MXE"), ",")[[1]]

MEASURES <- c(IJC_SAMPLE_1 = "incl_count", SJC_SAMPLE_1 = "skip_count", IncLevel1 = "psi")

# Runs where the command table's declared sample count exceeds the data's field count. Collected so
# the discrepancy is reported once at the end rather than only as scattered warnings.
.DROPPED <- list()

cmd  <- fread(cmd_file)
runs <- cmd[grepl(tf, out_folder, fixed = TRUE)]
stopifnot(nrow(runs) > 0L)

# In verify mode we need the analysis cohort, defined exactly as 02-3 defines it.
rna_to_use <- NULL
if (VERIFY) {
  # EXACTLY 02-3's definition (lines 36-44): RNA-Seq assays belonging to epirrs with >= 8 files
  # (the "full epigenome" criterion). Copied verbatim rather than approximated -- an approximate
  # cohort would make the verification fail for the wrong reason, or pass while comparing the
  # wrong rows.
  fm <- fread("processed_data/file_table.csv.gz")
  rna_to_use <- fm[
    assay_type == "RNA-Seq" &
      epirr_id_without_version %in%
        fm[, if (.N >= 8) .SD, by = epirr_id_without_version][, epirr_id_without_version],
    uuid
  ]
  # 441, not 415: rna_to_use is the QC/metadata cohort. 26 of those (the AMED-CREST gap) were never
  # quantified by rMATS, so intersecting with what the runs actually contain yields the modelled 415.
  cat(sprintf("verify mode: restricting to %d cohort uuids (expect 415 to survive the rMATS runs)\n",
    length(rna_to_use)))
}

# One run's contribution for one event type, as (ID, uuid, incl_count, skip_count, psi).
# NB the argument is `this_run`, not `run_name`: `runs[run_name == run_name]` would compare the
# column to itself and match every row, and the `..run_name` escape does not apply to `i`.
build_run <- function(this_run, event_type) {
  jf <- file.path(atlas_root, tf, this_run, sprintf("%s.MATS.JC.txt", event_type))
  if (!file.exists(jf)) return(NULL)
  # colClasses=character is LOAD-BEARING, not defensive. These columns are comma-separated
  # per-sample values, and fread's type inference reads a 2-sample value like "10,11" as the NUMBER
  # 10.11 -- taking the comma for a European decimal separator. The comma is destroyed, the field
  # collapses from 2 to 1, and the second sample silently disappears. It bites exactly the runs with
  # N == 2 ("10,11,12" is unambiguous, "10" is harmless), which in biotype_filtered is
  # single_fr-unstranded_{42,36,62}. Reading them as character preserves the separator.
  dt <- fread(jf, select = c("ID", names(MEASURES)),
    colClasses = setNames(rep("character", length(MEASURES)), names(MEASURES)))
  uuids <- strsplit(runs[run_name == this_run, uuid_string][1], ",", fixed = TRUE)[[1]]
  stopifnot(length(uuids) > 0L)

  # Width is measured from the DATA rather than trusted from uuid_string. NB the three runs this
  # once flagged (single_fr-unstranded_{42,36,62}) were NOT a real mismatch -- they were fread
  # dropping a comma (see colClasses above), and all 1,522 samples are quantified. The check stays
  # because a genuine declared-vs-actual gap would otherwise mislabel every column after it, but
  # with the read fixed it should now find nothing; if it fires, investigate before trusting output.
  n_fields <- length(strsplit(as.character(dt[[names(MEASURES)[1]]][1]), ",", fixed = TRUE)[[1]])
  if (n_fields != length(uuids)) {
    warning(sprintf(
      "%s / %s: uuid_string declares %d samples but the data has %d fields; dropping the %d trailing declared uuid(s): %s",
      event_type, this_run, length(uuids), n_fields, length(uuids) - n_fields,
      paste(utils::tail(uuids, length(uuids) - n_fields), collapse = ", ")),
      call. = FALSE, immediate. = TRUE)
    # Record BEFORE truncating: computing `declared` from the already-shortened vector made the
    # summary table report declared == fields == 1, i.e. no discrepancy, for the exact rows whose
    # purpose is to show one. The per-run warning above was right because it fires pre-truncation.
    .DROPPED[[length(.DROPPED) + 1L]] <<- data.table(
      event_type = event_type, run_name = this_run,
      declared = length(uuids), fields = n_fields)
    # Positional truncation is the only defensible mapping: rMATS emits fields in the order the BAMs
    # were passed, so the surviving fields are the LEADING uuids. Anything else would silently
    # relabel real counts with the wrong sample.
    uuids <- uuids[seq_len(n_fields)]
  }

  idx <- seq_along(uuids)
  if (!is.null(rna_to_use)) idx <- idx[uuids[idx] %in% rna_to_use]
  if (!length(idx)) return(NULL)

  # Chunk over SAMPLES. tstrsplit(keep=) materialises only the requested positions, so peak memory
  # is n_events x length(chunk) x 3, independent of how wide the run is.
  parts <- lapply(split(idx, ceiling(seq_along(idx) / SAMPLE_CHUNK)), function(chunk) {
    cols <- lapply(names(MEASURES), function(m) {
      tstrsplit(dt[[m]], ",", fixed = TRUE, keep = chunk, type.convert = TRUE)
    })
    names(cols) <- MEASURES
    rbindlist(lapply(seq_along(chunk), function(j) {
      data.table(
        ID         = dt$ID,
        uuid       = uuids[chunk[j]],
        incl_count = cols[["incl_count"]][[j]],
        skip_count = cols[["skip_count"]][[j]],
        psi        = cols[["psi"]][[j]]
      )
    }))
  })
  rbindlist(parts)
}

HEADER <- "ID,uuid,incl_count,skip_count,psi"

for (et in EVENT_TYPES) {
  # Per-run parts are the unit of work AND of resumption: a killed job re-runs only the runs it had
  # not finished, which matters because SE is hours and exbio-interactive caps at one day.
  pdir <- file.path(out_root, "parts", et)
  dir.create(pdir, recursive = TRUE, showWarnings = FALSE)
  final <- file.path(out_root, sprintf("%s.csv.gz", et))
  acc <- vector("list", nrow(runs))
  wrote <- character(0)
  for (i in seq_len(nrow(runs))) {
    rn <- runs$run_name[i]
    of <- file.path(pdir, sprintf("%s.csv.gz", rn))
    if (file.exists(of) && !VERIFY) {
      cat(sprintf("  %s / %s: part exists, skipping\n", et, rn)); wrote <- c(wrote, of); next
    }
    t0 <- Sys.time()
    d <- build_run(rn, et)
    if (is.null(d)) { cat(sprintf("  %s / %s: no cohort samples, skipped\n", et, rn)); next }
    if (VERIFY) { acc[[i]] <- d } else {
      # Parts are written HEADERLESS so the finished file is assembled by raw concatenation:
      # gzip members concatenate into a valid stream, so no part is ever decompressed again.
      # Re-compressing 14 GB just to insert one header line would dominate the runtime.
      #
      # `.csv.gz` must stay on the TEMP name too -- fwrite picks its compression from the file
      # extension, so a bare `.tmp` suffix silently writes plain CSV under a .gz name.
      tmp <- paste0(of, ".tmp", Sys.getpid(), ".csv.gz")
      fwrite(d, tmp, compress = "gzip", col.names = FALSE)
      file.rename(tmp, of)
      wrote <- c(wrote, of)
    }
    cat(sprintf("  %s / %-28s %10s rows  %.1f min\n", et, rn, format(nrow(d), big.mark = ","),
      as.numeric(difftime(Sys.time(), t0, units = "mins"))))
    rm(d); gc(verbose = FALSE)
  }

  if (!VERIFY) {
    if (!length(wrote)) stop("no parts produced for ", et)
    hdr <- file.path(out_root, sprintf(".header_%s.csv.gz", et))
    con <- gzfile(hdr, "wb"); writeLines(HEADER, con); close(con)
    tmp_final <- paste0(final, ".tmp", Sys.getpid())
    if (file.exists(tmp_final)) unlink(tmp_final)
    stopifnot(file.append(tmp_final, c(hdr, sort(wrote))))
    file.rename(tmp_final, final)
    unlink(hdr)
    # Read back the head: a concatenation error would otherwise surface only to whoever downloads
    # the release. Cheap -- decompresses one block.
    chk <- tryCatch(fread(final, nrows = 5L), error = function(e) NULL)
    if (is.null(chk) || !identical(names(chk), strsplit(HEADER, ",")[[1]])) {
      stop("assembled ", final, " is not readable with the expected header")
    }
    cat(sprintf("  -> %s (%d parts, %.2f GB)\n", final, length(wrote),
      file.info(final)$size / 1024^3))
  }

  if (VERIFY) {
    got <- rbindlist(Filter(Negate(is.null), acc))
    ref_file <- file.path(atlas_root, tf, sprintf("%s.MATS.JC.txt.csv.gz", et))
    if (!file.exists(ref_file)) { cat(sprintf("%s: no reference file, cannot verify\n", et)); next }
    ref <- fread(ref_file)
    setkey(got, ID, uuid); setkey(ref, ID, uuid)
    ok <- identical(dim(got), dim(ref)) && isTRUE(all.equal(got, ref, check.attributes = FALSE))
    cat(sprintf("\n=== VERIFY %s: rebuilt %s rows vs reference %s rows -- %s ===\n",
      et, format(nrow(got), big.mark = ","), format(nrow(ref), big.mark = ","),
      if (ok) "IDENTICAL" else "DIFFERS"))
    if (!ok) {
      cat("  the standalone build does not reproduce 02-3's output on the cohort subset.\n")
      cat("  DO NOT trust the full-cohort output until this is resolved.\n")
      print(all.equal(got, ref, check.attributes = FALSE))
      quit(status = 1)
    }
  }
}
if (length(.DROPPED)) {
  cat("\n=== DECLARED-vs-ACTUAL SAMPLE MISMATCHES ===\n")
  print(unique(rbindlist(.DROPPED)))
  cat("The rMATS command table declares more samples than the output contains for these runs.\n")
  cat("The atlas covers the QUANTIFIED samples, which is fewer than uuid_string implies.\n")
}
cat("\ndone\n")
