---
title: "rMATS to SUPPA"
author: "Quirin Manz"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
rmats_command_file <- "data/rmats_split_post_commands.tsv"
command_dt <- fread(rmats_command_file)
experiment_metadata <- fread("data/EpiATLAS_experiment_metadata.csv")
experiment_metadata[, experiment_type := factor(experiment_type)]
file_metadata <- fread("processed_data/file_table.csv.gz")
rna_to_use <- file_metadata[
  assay_type == "RNA-Seq" &
    epirr_id_without_version %in% file_metadata[,
      if (.N >= 8) .SD,
      by = epirr_id_without_version
    ][, epirr_id_without_version],
  uuid
]
# bam_dt[experiment_metadata[, epirr := epirr_id], on = .NATURAL, uuid := uuid]
```

```{r, fig.width=12, fig.height=8}
library(UpSetR)
library(grid)

# ID format for suppa: "ENSG00000000419.12;SE:chr20:50940933-50941129:50941209-50942031:-"
average_read_coverage <- 20
min_average_PSI <- .05
max_average_PSI <- 1 - min_average_PSI
min_read_coverage <- 10
min_samples_coverage <- 3
splicing_dir <- file.path("splicing_analysis", "rmats")
dir.create(splicing_dir, recursive = TRUE, showWarnings = FALSE)

rmats_dir <- file.path(data_dir, "rmats", "biotype_filtered")
event_type <- "SE"
junction_counts <- "MATS.JC.txt"
run_name <- "paired_fr-firststrand_75"
plot_dist <- TRUE

for (event_type in c("SE", "RI", "A3SS", "A5SS", "MXE")) {
  print(event_type)
  for (rmats_dir in list.dirs(file.path(data_dir, "rmats"), recursive = FALSE)
    # c( # "rmats_out_all", "rmats_out_2",
    #   "rmats_out" # , "rmats_out_3"
    # )
  ) {
    print(basename(rmats_dir))
    this_splicing_dir <- file.path(splicing_dir, basename(rmats_dir))
    dir.create(this_splicing_dir, recursive = TRUE, showWarnings = FALSE)
    for (junction_counts in c(
      "MATS.JC.txt" # , "MATS.JCEC.txt"
    )) {
      # read annotation file
      event_annotation <- fread(file.path(rmats_dir, command_dt[grep(basename(rmats_dir), out_folder), run_name][1], paste("fromGTF", event_type, "txt", sep = ".")))
      if (event_type == "SE") {
        event_annotation[, suppa_id := sprintf(
          "%s;%s:%s:%s-%s:%s-%s:%s",
          GeneID,
          event_type,
          chr,
          upstreamEE,
          exonStart_0base + 1,
          exonEnd,
          downstreamES + 1,
          strand
        )]
      } else if (event_type == "RI") {
        event_annotation[, suppa_id := sprintf(
          "%s;%s:%s:%s:%s-%s:%s:%s",
          GeneID,
          event_type,
          chr,
          upstreamES + 1,
          upstreamEE,
          downstreamES + 1,
          downstreamEE,
          strand
        )]
      } else if (event_type == "A3SS") {
        event_annotation[, suppa_id := sprintf(
          "%s;%s:%s:%s-%s:%s-%s:%s",
          GeneID,
          event_type,
          chr,
          ifelse(strand == "+", flankingEE, longExonEnd),
          ifelse(strand == "+", longExonStart_0base + 1, flankingES + 1),
          ifelse(strand == "+", flankingEE, shortEE),
          ifelse(strand == "+", shortES + 1, flankingES + 1),
          strand
        )]
      } else if (event_type == "A5SS") {
        event_annotation[, suppa_id := sprintf(
          "%s;%s:%s:%s-%s:%s-%s:%s",
          GeneID,
          event_type,
          chr,
          ifelse(strand == "+", longExonEnd, flankingEE),
          ifelse(strand == "+", flankingES + 1, longExonStart_0base + 1),
          ifelse(strand == "+", shortEE, flankingEE),
          ifelse(strand == "+", flankingES + 1, shortES + 1),
          strand
        )]
      } else if (event_type == "MXE") {
        event_annotation[, suppa_id := sprintf(
          "%s;%s:%s:%s-%s:%s-%s:%s-%s:%s-%s:%s",
          GeneID,
          event_type,
          chr,
          upstreamEE,
          `1stExonStart_0base` + 1,
          `1stExonEnd`,
          downstreamES + 1,
          upstreamEE,
          `2ndExonStart_0base` + 1,
          `2ndExonEnd`,
          downstreamES + 1,
          strand
        )]
      } else {
        stop("Not implemented yet")
      }

      event_sample_data_path <- file.path(rmats_dir, paste(event_type, junction_counts, "csv.gz", sep = "."))
      if (file.exists(event_sample_data_path)) {
        event_sample_data <- fread(file.path(rmats_dir, paste(event_type, junction_counts, "csv.gz", sep = ".")))
      } else {
        id_vars <-
          c(
            "ID"
          )
        measure_vars <-
          c("IJC_SAMPLE_1", "SJC_SAMPLE_1", "IncLevel1")
        dt_list <- pbmclapply(command_dt[grep(basename(rmats_dir), out_folder), run_name], function(this_run_name) {
          junction_file <- file.path(rmats_dir, this_run_name, paste(event_type, junction_counts, sep = "."))
          # read file with counts
          dt <-
            fread(junction_file, select = c(id_vars, measure_vars))
          # convert to long format

          long_dt <-
            melt(
              dt,
              id.vars = id_vars,
              measure.vars = measure_vars
            )
          # add sample names, by splitting by comma and retaining the order of which they appear in the rmats input file
          uuids <- command_dt[grep(basename(rmats_dir), out_folder) & run_name == this_run_name, strsplit(uuid_string, ",", fixed = TRUE)][[1]]
          long_dt[, (uuids) := tstrsplit(value, ",", fixed = TRUE, type.convert = TRUE)]
          # convert to even longer format to have one row per sample
          lapply(split(long_dt, long_dt[, variable]),
            melt,
            id.vars = c(id_vars, "variable"),
            measure.vars = uuids,
            variable.name = "uuid"
          )
        })
        names(dt_list) <- command_dt[grep(basename(rmats_dir), out_folder), run_name]
        long_dt_list <- sapply(measure_vars, function(measure_var) {
          rbindlist(sapply(dt_list, function(dt_split) {
            dt_split[[measure_var]]
          }, simplify = FALSE), idcol = "run_name")
        }, simplify = FALSE)

        stopifnot(identical(
          long_dt_list$IJC_SAMPLE_1[, .(ID, uuid)],
          long_dt_list$SJC_SAMPLE_1[, .(ID, uuid)]
        ))

        stopifnot(identical(
          long_dt_list$SJC_SAMPLE_1[, .(ID, uuid)],
          long_dt_list$IncLevel1[, .(ID, uuid)]
        ))

        event_sample_data <- long_dt_list$IJC_SAMPLE_1[, .(ID, uuid, incl_count = value)]
        event_sample_data[, skip_count := long_dt_list$SJC_SAMPLE_1[, value]]
        event_sample_data[, psi := long_dt_list$IncLevel1[, value]]

        fwrite(event_sample_data, event_sample_data_path)
      }

      # event_sample_data[, total_count := incl_count + skip_count]

      # # add experiment type
      event_sample_data[experiment_metadata, on = .(uuid), experiment_type := experiment_type]

      # compute average counts per event and per experiment type and event
      # recompute for the RNA used in this analysis as well
      uuids_to_filter_on <- list(all = event_sample_data[, unique(uuid)], full_epigenomes = rna_to_use)
      mapply(as.list(names(uuids_to_filter_on)), uuids_to_filter_on, FUN = function(filter_name, uuids_to_filter) {
        print(filter_name)
        average_dt <- Reduce(
          merge,
          pbmclapply(
            list(
              function() {
                rbind(
                  event_sample_data[uuid %in% uuids_to_filter, .(incl_sum = sum(incl_count, na.rm = TRUE), n_samples = .N), by = ID],
                  event_sample_data[uuid %in% uuids_to_filter, .(incl_sum = sum(incl_count, na.rm = TRUE), n_samples = .N), by = .(ID, experiment_type)],
                  fill = TRUE
                )
              },
              function() {
                rbind(
                  event_sample_data[uuid %in% uuids_to_filter, .(skip_sum = sum(skip_count, na.rm = TRUE)), by = ID],
                  event_sample_data[uuid %in% uuids_to_filter, .(skip_sum = sum(skip_count, na.rm = TRUE)), by = .(ID, experiment_type)],
                  fill = TRUE
                )
              },
              function() {
                rbind(
                  event_sample_data[uuid %in% uuids_to_filter, .(average_psi = mean(psi, na.rm = TRUE)), by = ID],
                  event_sample_data[uuid %in% uuids_to_filter, .(average_psi = mean(psi, na.rm = TRUE)), by = .(ID, experiment_type)],
                  fill = TRUE
                )
              }
            ),
            function(f) f(),
            mc.cores = 3
          )
        )
        average_dt[, average_count := (incl_sum + skip_sum) / n_samples]

        # scatterplot average count vs average PSI
        ggplot(average_dt, aes(x = average_count + 1, y = average_psi, color = experiment_type)) +
          geom_point(alpha = .5) +
          scale_x_log10() +
          # create a line y ~ x
          geom_smooth(method = "lm", se = FALSE) +
          ggpubr::stat_cor(method = "spearman", label.x.npc = "middle", label.y.npc = "bottom") +
          facet_wrap(~experiment_type) +
          labs(title = sprintf("Average Count vs Average PSI:"))

        # plot average count and PSI distributions
        if (plot_dist) {
          print(
            ggplot(
              average_dt,
              aes(x = average_count + 1, color = experiment_type)
            ) +
              geom_line(aes(y = 1 - after_stat(y)), stat = "ecdf") +
              scale_x_log10() +
              geom_vline(xintercept = average_read_coverage + 1) +
              labs(title = sprintf("Average Read Coverage: with line at %d; %s %s %s", average_read_coverage + 1, event_type, basename(rmats_dir), filter_name))
          )
          print(
            ggplot(average_dt, aes(x = average_psi, fill = experiment_type)) +
              geom_histogram(position = "dodge") +
              geom_vline(xintercept = c(min_average_PSI, max_average_PSI)) +
              labs(title = sprintf("Average PSI: %s %s %s", event_type, basename(rmats_dir), filter_name))
          )
          print(
            ggplot(
              average_dt[average_psi >= min_average_PSI &
                average_psi <= max_average_PSI],
              aes(x = average_psi, fill = experiment_type)
            ) +
              geom_histogram(position = "dodge", binwidth = .05) +
              geom_vline(xintercept = c(min_average_PSI, max_average_PSI)) +
              labs(title = sprintf("Average PSI: %f <= PSI < %f; %s %s %s", min_average_PSI, max_average_PSI, event_type, basename(rmats_dir), filter_name))
          )

          ### Check per-sample read coverage filtering ----
          # Step 1: Compute total counts per event/sample

          # Step 2: Create grid of thresholds to test
          min_read_cutoffs <- c(0, 1, 5, 10, 15, 20)
          min_sample_cutoffs <- c(1, 3, 5, 10)

          # Step 3: Expand combinations and compute how many events pass
          plot_dt <- CJ(
            min_read_coverage = min_read_cutoffs,
            min_samples_coverage = min_sample_cutoffs
          )

          plot_dt[, n_pass := event_sample_data[
            uuid %in% uuids_to_filter &
              incl_count + skip_count >= min_read_coverage,
            .N,
            by = ID
          ][N >= min_samples_coverage, .N],
          by = .(min_read_coverage, min_samples_coverage)
          ]

          print(ggplot(plot_dt, aes(
            x = min_samples_coverage, y = n_pass,
            color = factor(min_read_coverage)
          )) +
            geom_line() +
            geom_point() +
            labs(
              title = sprintf("%s %s %s", event_type, basename(rmats_dir), filter_name),
              x = "Minimum number of samples with sufficient read count",
              y = "Number of events (ID) retained",
              color = "Min per-sample read count"
            ))

          ###  Check average read coverages and PSI filtering ----

          # Step 1: Create grid of thresholds to test
          min_PSI_cutoffs <- seq(0, 0.05, by = 0.01)

          plot_dt <- CJ(
            average_read_coverage = min_read_cutoffs,
            min_average_PSI = min_PSI_cutoffs
          )

          plot_dt[, n_pass := average_dt[
            !is.na(experiment_type) &
              average_count >= average_read_coverage &
              average_psi >= min_average_PSI &
              average_psi <= 1 - min_average_PSI,
            ID,
            by = experiment_type
          ][duplicated(ID), .N],
          by = .(average_read_coverage, min_average_PSI)
          ]

          print(ggplot(plot_dt, aes(
            x = min_average_PSI, y = n_pass,
            color = factor(average_read_coverage)
          )) +
            geom_line() +
            geom_point() +
            labs(
              title = sprintf("Min averages per experiment type: %s %s %s", event_type, basename(rmats_dir), filter_name),
              x = "Minimum average PSI",
              y = "Number of events (ID) retained",
              color = "Min average read coverage"
            ))
        }
        # get IDs to keep based on average PSI and average read coverage
        keep_ids_orig <-
          average_dt[
            !is.na(experiment_type) &
              average_count >= average_read_coverage &
              average_psi >= min_average_PSI &
              average_psi <= 1 - min_average_PSI,
            ID,
            by = experiment_type
          ][duplicated(ID), ID]
        length(keep_ids_orig)
        # number of unique IDs passing the filter across all experiment types
        average_dt[
          is.na(experiment_type) &
            average_count >= average_read_coverage &
            average_psi >= min_average_PSI &
            average_psi <= 1 - min_average_PSI,
          uniqueN(ID)
        ]

        # intersect(
        #   average_psi_dt[!is.na(experiment_type) &
        #     average_psi >= min_average_PSI &
        #     average_psi <= max_average_PSI, ID, by = experiment_type][duplicated(ID), ID],
        #   average_count_dt[!is.na(experiment_type) &
        #     average_count >= average_read_coverage, ID, by = experiment_type][duplicated(ID), ID]
        # )

        keep_ids_min_sample <- event_sample_data[uuid %in% uuids_to_filter & incl_count + skip_count >= min_read_coverage, .N, by = ID][N >= min_samples_coverage, ID]

        upset <- upset(
          fromList(list(orig = keep_ids_orig, min_sample = keep_ids_min_sample)),
          nsets = 2,
          order.by = "freq",
          mainbar.y.label = "Number of events (ID)",
          sets.x.label = "Total events (ID)"
        )
        print(upset)
        grid.text(sprintf("%s %s %s", event_type, basename(rmats_dir), filter_name), x = 0.65, y = 0.95, gp = gpar(fontsize = 20))

        event_sample_data[event_annotation, on = .(ID), suppa_id := suppa_id]
        # long_long_dt[bam_dt, on = .NATURAL, uuid := uuid]
        suppa_format_dt <- dcast(event_sample_data[ID %in% keep_ids_orig & uuid %in% uuids_to_filter], suppa_id ~ uuid, value.var = "psi")
        suppa_file <- file.path(this_splicing_dir, paste0(ifelse(filter_name == "all", filter_name, ""), "event_", substr(event_type, 1, 2), ".psi"))
        write.table(as.data.frame(suppa_format_dt[, -"suppa_id"], row.names = suppa_format_dt[, suppa_id]), suppa_file, sep = "\t", quote = FALSE)
        fwrite(unique(event_annotation[, .(ID, geneSymbol, suppa_id)]), paste0(suppa_file, ".annot"))
      })

      ### PCA ----
      # long_long_dt[average_psi_dt, on = .NATURAL, average_psi := average_psi]
      # long_long_dt[, imputed_value := value]
      # long_long_dt[is.na(imputed_value) &
      #   variable == "IncLevel1", imputed_value := average_psi]
      # for (keep_ids_name in c("orig", "min_sample")) {
      #   keep_ids <- get(paste0("keep_ids_", keep_ids_name))
      #   for (col in c("value", "imputed_value")) {
      #     event_mat <-
      #       as.matrix(
      #         dcast(long_long_dt[ID %in% keep_ids &
      #           variable == "IncLevel1"], sample_name ~ ID, value.var = col),
      #         rownames = "sample_name"
      #       )

      #     for (i in 1:ncol(event_mat)) {
      #       event_mat[is.na(event_mat[, i]), i] <-
      #         mean(event_mat[, i], na.rm = TRUE)
      #     }
      #     event_pca <- rsvd::rpca(event_mat, 4)
      #     rsvd::ggscreeplot(event_pca)
      #     variance <- event_pca$sdev^2
      #     explained_variance_ratio <- round(variance / event_pca$var, 3) * 100
      #     plot_dt <- as.data.table(event_pca$x, keep.rownames = "uuid")
      #     setnames(plot_dt, c("V1", "V2"), c("PC1", "PC2"))
      #     print(rsvd::ggindplot(
      #       event_pca,
      #       groups = unlist(tstrsplit(rownames(event_mat), "_", keep = 2)),
      #       ind_labels = FALSE
      #     ) + labs(title = paste(junction_file, keep_ids_name, col)))
      #     print(rsvd::ggindplot(
      #       event_pca,
      #       pcs = c(1, 3),
      #       groups = unlist(tstrsplit(rownames(event_mat), "_", keep = 2)),
      #       ind_labels = FALSE
      #     ) + labs(title = paste(junction_file, keep_ids_name, col)))
      #   }
    }
  }
}
```
