---
title: "a few tests"
output: pdf_document
---

```{r}
library(rtracklayer)
library(AnnotationDbi)
library(org.Hs.eg.db)
library(GO.db)
library(RSQLite)
library(DBI)
```



```{r liftOverTest}
## lift over stuff
# chain file: http://hgdownload.soe.ucsc.edu/goldenPath/hg19/liftOver/
chain <- import('data/hg19ToHg38.over.chain')
hg19 <- rtracklayer::import('data/human_permissive_enhancers_phase_1_and_2.bed')
lift <- unlist(rtracklayer::liftOver(hg19, chain))
lift <- sortSeqlevels(lift)
lift <- sort(lift)

hg38 <- rtracklayer::import('data/F5.hg38.enhancers.bed')
hg38 <- sortSeqlevels(hg38)
hg38 <- sort(hg38)
lift
hg38

```

```{r}
protein_id <- 'UNIPROT'
# first get splicing factors
go_id_splicing <- AnnotationDbi::select(GO.db, keys = c("mRNA splicing, via spliceosome"), columns = c("GOID"), keytype = c("TERM"))$GOID
splicing_factors <- unique(AnnotationDbi::select(org.Hs.eg.db, keys=go_id_splicing, columns = protein_id, keytype = "GOALL")[[protein_id]])
# here we manually produced data/splicing_factor_mapping.tab

# now get tfs
go_id_transcription_factor <- AnnotationDbi::select(GO.db, keys = c("DNA-binding transcription factor activity"), columns = c("GOID"), keytype = c("TERM"))$GOID
transcription_factors <- unique(AnnotationDbi::select(org.Hs.eg.db, keys=go_id_transcription_factor, columns = protein_id, keytype = "GOALL")[[protein_id]])
# here we manually produced data/transcription_factor_mapping.tab

```


```{r}

sf_mapping <- fread('data/splicing_factor_mapping.tab')
tf_mapping <- fread('data/transcription_factor_mapping.tab')
ppi <- fread('data/hippie_current.txt')
names(ppi) <- c('entry1', 'ncbi1', 'entry2', 'ncbi2', 'score', 'additional')
sf_tf_interaction <- ppi[(entry1 %in% sf_mapping[, `Entry name`] & entry2 %in% tf_mapping[, `Entry name`]) | (entry1 %in% tf_mapping[, `Entry name`] & entry2 %in% sf_mapping[, `Entry name`])]
tf_in_sf <- tf_mapping[, `Entry name`][tf_mapping[, `Entry name`] %in% sf_tf_interaction[, unique(c(entry1, entry2))]]
tf_mapping[`Entry name` %in% tf_in_sf, Entry]
uniprot_symbol <- setDT(AnnotationDbi::select(org.Hs.eg.db, keys=tf_mapping[`Entry name` %in% tf_in_sf, Entry], columns = "SYMBOL", keytype = protein_id))
```

```{r}
jaspar <- dbConnect(drv=RSQLite::SQLite(), dbname='data/JASPAR2022.sqlite3')
# tables <- dbListTables(jaspar)
# sapply(tables, dbListFields, conn=jaspar, simplify = FALSE)
all_matrices <- setDT(dbReadTable(jaspar, 'MATRIX'))
dbDisconnect(jaspar)
jaspar_symbol <- all_matrices[COLLECTION=='CORE', .(SYMBOL=unlist(tstrsplit(NAME, '::', fixed=TRUE))), by=.(BASE_ID, VERSION)]
jaspar_symbol[, ID_VERSION:=paste(BASE_ID, VERSION, sep = '.')]
ids_to_read <- jaspar_symbol[SYMBOL %in% uniprot_symbol$SYMBOL, unique(ID_VERSION)]
beds_to_read <- file.path('data', 'bed', paste0(ids_to_read, '.bed'))
beds_to_read <- beds_to_read[file.exists(beds_to_read)]
jaspar_beds <- sapply(beds_to_read, rtracklayer::import, simplify = FALSE)
jaspar_beds_hg38 <- sapply(jaspar_beds, function(x) unlist(rtracklayer::liftOver(x, chain=chain)))
```

